[project]
name = "car-sales-dashboard"
version = "0.1.0"
description = "Analytical dashboard for used cars"
authors = [
    {name = "Jakub Hána"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas (>=2.3.3,<3.0.0)",
    "dash (>=3.3.0,<4.0.0)",
    "plotly (>=6.5.0,<7.0.0)",
    "dash-bootstrap-components (>=2.0.4,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
